version: '3.3'

services:
  prod-demo:
    build:
      context: ./demo-ml
      dockerfile: prod.dockerfile
    container_name: PROD-demo-ml
    ports: 
      - "80:80"
    volumes: 
      - type: bind
        source: ./demo
        target: /app
      - type: volume
        source: prod_demo_volume
        target: /app/node_modules
    networks: 
      - prod-demo-network

networks: 
  prod-demo-network:

volumes:
  prod_demo_volume:
  